### ISSUE TITLE
missing bootstrap.js file

### ISSUE THREAD

**Issue by mlmarius** [dcartertwo/gulp-angular-browserify-seed#11]
there seems to be a missing file. i can't use the gulp task because of this. The file is required in main.js.

**Comment by zhangnanMoo** [comment]
me too....

➜  gulp-angular-browserify-seed git:(master) ✗ gulp
[14:56:59] Using gulpfile ~/myProject/gulp-angular-browserify-seed/gulpfile.js
[14:56:59] Starting 'default'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
[14:56:59] Starting 'clean'...
[14:56:59] Finished 'clean' after 5.04 ms
[14:56:59] Starting 'browserify'...
[14:56:59] Finished 'browserify' after 3.36 ms
[14:56:59] Starting 'lint'...
[14:56:59] Finished 'lint' after 1.92 ms
[14:56:59] Finished 'default' after 12 ms

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: module "./bootstrap" not found from "/Users/zhangnan/myProject/gulp-angular-browserify-seed/app/app/fake_f579beff.js"
    at /Users/zhangnan/myProject/gulp-angular-browserify-seed/node_modules/gulp-browserify/node_modules/browserify/index.js:570:23
    at /Users/zhangnan/myProject/gulp-angular-browserify-seed/node_modules/gulp-browserify/node_modules/browserify/node_modules/browser-resolve/index.js:185:24
    at /Users/zhangnan/myProject/gulp-angular-browserify-seed/node_modules/gulp-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:36:22
    at load (/Users/zhangnan/myProject/gulp-angular-browserify-seed/node_modules/gulp-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:54:43)
    at /Users/zhangnan/myProject/gulp-angular-browserify-seed/node_modules/gulp-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:22
    at /Users/zhangnan/myProject/gulp-angular-browserify-seed/node_modules/gulp-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:16:47
    at Object.oncomplete (fs.js:107:15)
